### ISSUE TITLE
api相关问题

### ISSUE THREAD

**Issue by luoysuan** [ImZjm/LeagueFast#1]
大佬看你代码里面有个websocke的订阅功能，用来接受对局，但是我看拳头的官网，并没有找到相关的文档，能否提供一下链接给我，十分感谢。

**Comment by ImZjm** [comment]
https://hextechdocs.dev/tag/lcu/

**Comment by luoysuan** [comment]
> https://hextechdocs.dev/tag/lcu/
好的 谢谢大佬
